// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhKv53dGAiT_doc4REZAgcwx2ePma9KnY',
    appId: '1:448892257654:web:d5da6191a620a5c012a657',
    messagingSenderId: '448892257654',
    projectId: 'mob13-2cfc4',
    authDomain: 'mob13-2cfc4.firebaseapp.com',
    databaseURL: 'https://mob13-2cfc4-default-rtdb.firebaseio.com',
    storageBucket: 'mob13-2cfc4.firebasestorage.app',
    measurementId: 'G-V4HCVHYK07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjitfrbxqmn49VQmtIifiM_GQfj3z2qvw',
    appId: '1:448892257654:android:e641e855b41b7c9c12a657',
    messagingSenderId: '448892257654',
    projectId: 'mob13-2cfc4',
    databaseURL: 'https://mob13-2cfc4-default-rtdb.firebaseio.com',
    storageBucket: 'mob13-2cfc4.firebasestorage.app',
  );
}
